name: Test
on: 
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A cheerful words
jobs:
  manual:
    run:
      runs-on: ubuntu-latest
      steps: 
        - run: echo "${{ inputs.greeting }}"
